language: scala
scala:
  - 2.10.5
  - 2.11.6
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
# sudo: false
script:
  - sbt mimaReportBinaryIssues
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
