language: scala

scala:
  - 2.11.12
  - 2.12.6
  - 2.13.0-M4

jdk:
  - oraclejdk8

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

env:
  global:
    - COURSIER_PROGRESS=0
    - secure: gYw+NTUc3uR9fGjXNFU3AWEzk6V3hh1ZZlWA+Cp7QagRWPyPsuq9zdXYmpNH60EN9IlC73+qd6xEO/szejgQfY7BN1THr+NPzHTSJzR0ZtytR/C3IROvkvMiqnc8TtvjH/ECEyDauRvNGDR1y2T7mOZcwYZlgvk99D1S1JuBNe0=
    - secure: WUTPbVxp6LhGYXdLYg1rNCsLnPdpoqxyOnND6oFZ11ffOCwb7eLlBjPwobt1iQlNLTw8ZTdsJ3IyE9+CVlgfSWVSi0BLDcpNcZcx1Mg1m37JPTp+3r/xExo8fjYySWlQfXmlnRoeZc0kfX5d3/bKlRpNEl/fZGeitSWDeEyGjzc=
    - PUBLISH=true

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -Dfs2.test.verbose coreJVM/compile
